CREATE TABLE punch_list.pendency (
    id bigserial not null,
    id_contract bigint not null,
    area_identification text not null,
    tag text null,
    description text not null,
    priority text not null,
    discipline text not null,
    status text not null,
    registered_by bigint not null,
    created_at datetime not null default CURRENT_TIMESTAMP,
    modified_in datetime not null default CURRENT_TIMESTAMP,
    registered_to bigint not null,
    expected_in datetime,
    finished_by bigint null,
    finished_at datetime,
    disapproved_by bigint null,
    disapproved_at datetime null,
    canceled_by bigint null,
    canceled_at datetime null,
    constraint pendency_pk primary key (id),
    constraint fk_pendency_registered_by foreign key (registered_by) references punch_list.responsible_person(id),
    constraint fk_pendency_registered_to foreign key (registered_to) references punch_list.responsible_person(id),
    constraint fk_pendency_finished_by foreign key (finished_by) references punch_list.responsible_person(id),
    constraint fk_pendency_disapproved_by foreign key (disapproved_by) references punch_list.responsible_person(id),
    constraint fk_pendency_canceled_by foreign key (canceled_by) references punch_list.responsible_person(id),
    constraint fk_pendency_id_contract foreign key (id_contract) references punch_list.contract(id)
);
